export const CommonConstants = <const>{
  USER_ADMINISTRATOR: "administrator",
  COMMON_NODATA: "Common.NoData",
  COMMON_STATUS0: "Common.Status0",
  COMMON_STATUS1: "Common.Status1",
  COMMON_STATUS2: "Common.Status2",
  COMMON_STATUS3: "Common.Status3",
  COMMON_STATUS4: "Common.Status4",
}

export const IconButton = <const>{
  EXCEL: 'fa fa-file-excel-o',
  WORD: 'fa fa-file-word-o',
  POWERPOINT: 'fa fa-file-powerpoint-o',
  PDF: 'fa fa-file-pdf-o',
  IMAGE: 'fa fa-file-image-o',
  VIDEO: 'fa fa-file-video-o',
  ADD: 'fa fa-plus',
  EDIT: 'fa fa-pencil-square-o',
  DELETE: 'fa fa-trash-o',
  SEARCH: 'fa fa-search',
  CLEAR: 'fa fa-ban',
  CLOSE: 'fa fa-times',
  RESET: 'fa fa-refresh',
  BACK: 'fa fa-chevron-left',
  SAVE: 'fa fa-check',
  SUBMIT: 'fa fa-check',
  LOCK: 'fa fa-lock',
  CALENDAR: 'fa fa-calendar',
  UPLOAD: 'fa fa-upload',
  CLOUDUPLOAD: 'fa fa-cloud-upload',
  DOWNLOAD: 'fa fa-download',
  CLOUDDOWNLOAD: 'fa fa-cloud-download',
  REMOVE: 'fa fa-remove',
  VIEW: 'fa fa-info',
  UPDATE: 'fa fa-check-square-o',
  BOOKMARK: 'fa fa-bookmark',
  DISABLED: 'fa fa-eye-slash',
  ARROW_RIGHT: 'fa fa-arrow-circle-right'
};