// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace eTierV2_API.Models
{
    /// <summary>
    /// &#24288;&#12289;&#29983;&#29986;&#32218;&#12289;&#29983;&#29986;&#37096;&#38272;&#32080;&#27083;&#38364;&#20418;&#27284;
    /// </summary>
    public partial class MES_Org
    {
        /// <summary>
        /// 廠別
        /// </summary>
        [Key]
        [StringLength(1)]
        public string Factory_ID { get; set; }
        /// <summary>
        /// &#29983;&#29986;&#37096;
        /// </summary>
        [Key]
        [StringLength(1)]
        public string PDC_ID { get; set; }
        /// <summary>
        /// &#29983;&#29986;&#32218;&#21029;
        /// </summary>
        [Key]
        [StringLength(3)]
        public string Line_ID { get; set; }
        /// <summary>
        /// &#29983;&#29986;&#37096;&#38272;
        /// </summary>
        [Key]
        [StringLength(4)]
        public string Dept_ID { get; set; }
        /// <summary>
        /// &#26847;&#21029;(&#23660;&#24615;)
        /// </summary>
        [StringLength(10)]
        public string Building { get; set; }
        /// <summary>
        /// &#32218;&#21029;&#25490;&#24207;
        /// </summary>
        public int? Line_Seq { get; set; }
        /// <summary>
        /// &#29376;&#24907;
        /// </summary>
        public int? Status { get; set; }
        /// <summary>
        /// &#30064;&#21205;&#26178;&#38291;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
        /// <summary>
        /// &#30064;&#21205;&#32773;
        /// </summary>
        [StringLength(16)]
        public string Updated_By { get; set; }
        /// <summary>
        /// HP&#30340;&#23565;&#25033;&#37096;&#38272;
        /// </summary>
        [Required]
        [StringLength(4)]
        public string HP_Dept_ID { get; set; }
        /// <summary>
        /// &#26159;&#21542;&#21487;&#20197;&#20351;&#29992;AGV
        /// </summary>
        public int? IsAGV { get; set; }
        /// <summary>
        /// Block
        /// </summary>
        [StringLength(1)]
        public string Block { get; set; }
        /// <summary>
        /// &#20013;&#32218;
        /// </summary>
        [StringLength(3)]
        public string Line_ID_2 { get; set; }
        /// <summary>
        /// &#26159;&#21542;&#28858;T1T3&#20351;&#29992;&#30340;&#32218;&#21029;
        /// </summary>
        public int? IsT1T3 { get; set; }
        [Column(TypeName = "numeric(3, 1)")]
        public decimal? Weight { get; set; }
    }
}