// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models;

public partial class P_ThongTinViTriCauThu
{
    [Key]
    public int ID { get; set; }

    public int? ThongTinID { get; set; }

    public int? ViTriID { get; set; }
}