// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models;

public partial class P_ThuocTinhBaiTap
{
    [Key]
    public int IDBaiTap { get; set; }

    [Key]
    public int IDThuocTinhChinh { get; set; }
}