// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models;

public partial class ThuocTinhChinh
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    public string TenThuocTinh { get; set; }

    public int? Loai { get; set; }
}