using API.Models;

namespace API._Repositories
{
    public interface IRepositoryAccessor : IRepositoryAccessorBase
    {
        IRepository<HP_CharacterMap> HP_CharacterMap { get; }
        IRepository<HP_g26> HP_g26 { get; }
        IRepository<HP_g33> HP_g33 { get; }
        IRepository<HP_g35b> HP_g35b { get; }
        IRepository<HP_g36> HP_g36 { get; }
        IRepository<HP_g37> HP_g37 { get; }
        IRepository<HP_g59c> HP_g59c { get; }
        IRepository<HP_HRMS_Emp_Personal_g01> HP_HRMS_Emp_Personal_g01 { get; }
        IRepository<HP_j02> HP_j02 { get; }
        IRepository<HP_y14> HP_y14 { get; }
        IRepository<HRMS_Att_Annual_Leave> HRMS_Att_Annual_Leave { get; }
        IRepository<HRMS_Att_Calendar> HRMS_Att_Calendar { get; }
        IRepository<HRMS_Att_Change_Reason> HRMS_Att_Change_Reason { get; }
        IRepository<HRMS_Att_Change_Record> HRMS_Att_Change_Record { get; }
        IRepository<HRMS_Att_Female_Menstrual_Hours> HRMS_Att_Female_Menstrual_Hours { get; }
        IRepository<HRMS_Att_Leave_Application> HRMS_Att_Leave_Application { get; }
        IRepository<HRMS_Att_Leave_Maintain> HRMS_Att_Leave_Maintain { get; }
        IRepository<HRMS_Att_Loaned_Monthly> HRMS_Att_Loaned_Monthly { get; }
        IRepository<HRMS_Att_Loaned_Monthly_Detail> HRMS_Att_Loaned_Monthly_Detail { get; }
        IRepository<HRMS_Att_Lunchtime> HRMS_Att_Lunchtime { get; }
        IRepository<HRMS_Att_Monthly> HRMS_Att_Monthly { get; }
        IRepository<HRMS_Att_Monthly_Detail> HRMS_Att_Monthly_Detail { get; }
        IRepository<HRMS_Att_Monthly_Period> HRMS_Att_Monthly_Period { get; }
        IRepository<HRMS_Att_Overtime_Application> HRMS_Att_Overtime_Application { get; }
        IRepository<HRMS_Att_Overtime_Maintain> HRMS_Att_Overtime_Maintain { get; }
        IRepository<HRMS_Att_Overtime_Parameter> HRMS_Att_Overtime_Parameter { get; }
        IRepository<HRMS_Att_Overtime_Temp> HRMS_Att_Overtime_Temp { get; }
        IRepository<HRMS_Att_Posting> HRMS_Att_Posting { get; }
        IRepository<HRMS_Att_Pregnancy_Data> HRMS_Att_Pregnancy_Data { get; }
        IRepository<HRMS_Att_Probation_Monthly> HRMS_Att_Probation_Monthly { get; }
        IRepository<HRMS_Att_Probation_Monthly_Detail> HRMS_Att_Probation_Monthly_Detail { get; }
        IRepository<HRMS_Att_Resign_Monthly> HRMS_Att_Resign_Monthly { get; }
        IRepository<HRMS_Att_Resign_Monthly_Detail> HRMS_Att_Resign_Monthly_Detail { get; }
        IRepository<HRMS_Att_Swipe_Card> HRMS_Att_Swipe_Card { get; }
        IRepository<HRMS_Att_Swipecard_Set> HRMS_Att_Swipecard_Set { get; }
        IRepository<HRMS_Att_Temp_Record> HRMS_Att_Temp_Record { get; }
        IRepository<HRMS_Att_Use_Monthly_Leave> HRMS_Att_Use_Monthly_Leave { get; }
        IRepository<HRMS_Att_Work_Shift> HRMS_Att_Work_Shift { get; }
        IRepository<HRMS_Att_Work_Shift_Change> HRMS_Att_Work_Shift_Change { get; }
        IRepository<HRMS_Att_Work_Type_Days> HRMS_Att_Work_Type_Days { get; }
        IRepository<HRMS_Att_Yearly> HRMS_Att_Yearly { get; }
        IRepository<HRMS_Att_SwipeCard_Anomalies_Set> HRMS_Att_SwipeCard_Anomalies_Set { get; }
        IRepository<HRMS_Basic_Account> HRMS_Basic_Account { get; }
        IRepository<HRMS_Basic_Account_Role> HRMS_Basic_Account_Role { get; }
        IRepository<HRMS_Basic_Code> HRMS_Basic_Code { get; }
        IRepository<HRMS_Basic_Code_Language> HRMS_Basic_Code_Language { get; }
        IRepository<HRMS_Basic_Code_Type> HRMS_Basic_Code_Type { get; }
        IRepository<HRMS_Basic_Code_Type_Language> HRMS_Basic_Code_Type_Language { get; }
        IRepository<HRMS_Basic_Factory_Comparison> HRMS_Basic_Factory_Comparison { get; }
        IRepository<HRMS_Basic_Level> HRMS_Basic_Level { get; }
        IRepository<HRMS_Basic_Role> HRMS_Basic_Role { get; }
        IRepository<HRMS_Basic_Role_Program_Group> HRMS_Basic_Role_Program_Group { get; }
        IRepository<HRMS_Emp_Blacklist> HRMS_Emp_Blacklist { get; }
        IRepository<HRMS_Emp_Certification> HRMS_Emp_Certification { get; }
        IRepository<HRMS_Emp_Contract_Management> HRMS_Emp_Contract_Management { get; }
        IRepository<HRMS_Emp_Contract_Type> HRMS_Emp_Contract_Type { get; }
        IRepository<HRMS_Emp_Contract_Type_Detail> HRMS_Emp_Contract_Type_Detail { get; }
        IRepository<HRMS_Emp_Dependent> HRMS_Emp_Dependent { get; }
        IRepository<HRMS_Emp_Document> HRMS_Emp_Document { get; }
        IRepository<HRMS_Emp_Educational> HRMS_Emp_Educational { get; }
        IRepository<HRMS_Emp_Educational_File> HRMS_Emp_Educational_File { get; }
        IRepository<HRMS_Emp_Emergency_Contact> HRMS_Emp_Emergency_Contact { get; }
        IRepository<HRMS_Emp_Exit_History> HRMS_Emp_Exit_History { get; }
        IRepository<HRMS_Emp_External_Experience> HRMS_Emp_External_Experience { get; }
        IRepository<HRMS_Emp_File> HRMS_Emp_File { get; }
        IRepository<HRMS_Emp_Group> HRMS_Emp_Group { get; }
        IRepository<HRMS_Emp_IDcard_EmpID_History> HRMS_Emp_IDcard_EmpID_History { get; }
        IRepository<HRMS_Emp_Identity_Card_History> HRMS_Emp_Identity_Card_History { get; }
        IRepository<HRMS_Emp_Permission_Group> HRMS_Emp_Permission_Group { get; }
        IRepository<HRMS_Emp_Personal> HRMS_Emp_Personal { get; }
        IRepository<HRMS_Emp_Rehire_Evaluation> HRMS_Emp_Rehire_Evaluation { get; }
        IRepository<HRMS_Emp_Resignation> HRMS_Emp_Resignation { get; }
        IRepository<HRMS_Emp_Resignation_History> HRMS_Emp_Resignation_History { get; }
        IRepository<HRMS_Emp_Skill> HRMS_Emp_Skill { get; }
        IRepository<HRMS_Emp_Transfer_History> HRMS_Emp_Transfer_History { get; }
        IRepository<HRMS_Emp_Transfer_Operation> HRMS_Emp_Transfer_Operation { get; }
        IRepository<HRMS_Emp_Unpaid_Leave> HRMS_Emp_Unpaid_Leave { get; }
        IRepository<HRMS_Ins_Benefits_Maintain> HRMS_Ins_Benefits_Maintain { get; }
        IRepository<HRMS_Ins_Emp_Maintain> HRMS_Ins_Emp_Maintain { get; }
        IRepository<HRMS_Ins_Rate_Setting> HRMS_Ins_Rate_Setting { get; }
        IRepository<HRMS_Org_Department> HRMS_Org_Department { get; }
        IRepository<HRMS_Org_Department_Language> HRMS_Org_Department_Language { get; }
        IRepository<HRMS_Org_Direct_Department> HRMS_Org_Direct_Department { get; }
        IRepository<HRMS_Org_Direct_Section> HRMS_Org_Direct_Section { get; }
        IRepository<HRMS_Org_Work_Type_Headcount> HRMS_Org_Work_Type_Headcount { get; }
        IRepository<HRMS_Rew_EmpRecords> HRMS_Rew_EmpRecords { get; }
        IRepository<HRMS_Rew_ReasonCode> HRMS_Rew_ReasonCode { get; }
        IRepository<HRMS_Sal_AddDedItem_AccountCode> HRMS_Sal_AddDedItem_AccountCode { get; }
        IRepository<HRMS_Sal_AddDedItem_Monthly> HRMS_Sal_AddDedItem_Monthly { get; }
        IRepository<HRMS_Sal_AddDedItem_Settings> HRMS_Sal_AddDedItem_Settings { get; }
        IRepository<HRMS_Sal_Bank_Account> HRMS_Sal_Bank_Account { get; }
        IRepository<HRMS_Sal_Childcare_Subsidy> HRMS_Sal_Childcare_Subsidy { get; }
        IRepository<HRMS_Sal_Close> HRMS_Sal_Close { get; }
        IRepository<HRMS_Sal_Currency_Rate> HRMS_Sal_Currency_Rate { get; }
        IRepository<HRMS_Sal_Dept_SAPCostCenter_Mapping> HRMS_Sal_Dept_SAPCostCenter_Mapping { get; }
        IRepository<HRMS_Sal_History> HRMS_Sal_History { get; }
        IRepository<HRMS_Sal_History_Detail> HRMS_Sal_History_Detail { get; }
        IRepository<HRMS_Sal_History_Test> HRMS_Sal_History_Test { get; }
        IRepository<HRMS_Sal_Item_Settings> HRMS_Sal_Item_Settings { get; }
        IRepository<HRMS_Sal_Leave_Calc_Maintenance> HRMS_Sal_Leave_Calc_Maintenance { get; }
        IRepository<HRMS_Sal_Master> HRMS_Sal_Master { get; }
        IRepository<HRMS_Sal_Master_Detail> HRMS_Sal_Master_Detail { get; }
        IRepository<HRMS_Sal_MasterBackup> HRMS_Sal_MasterBackup { get; }
        IRepository<HRMS_Sal_MasterBackup_Detail> HRMS_Sal_MasterBackup_Detail { get; }
        IRepository<HRMS_Sal_Monthly> HRMS_Sal_Monthly { get; }
        IRepository<HRMS_Sal_Monthly_Detail> HRMS_Sal_Monthly_Detail { get; }
        IRepository<HRMS_Sal_Parameter> HRMS_Sal_Parameter { get; }
        IRepository<HRMS_Sal_Payslip_Email> HRMS_Sal_Payslip_Email { get; }
        IRepository<HRMS_Sal_Probation_MasterBackup> HRMS_Sal_Probation_MasterBackup { get; }
        IRepository<HRMS_Sal_Probation_MasterBackup_Detail> HRMS_Sal_Probation_MasterBackup_Detail { get; }
        IRepository<HRMS_Sal_Probation_Monthly> HRMS_Sal_Probation_Monthly { get; }
        IRepository<HRMS_Sal_Probation_Monthly_Detail> HRMS_Sal_Probation_Monthly_Detail { get; }
        IRepository<HRMS_Sal_Resign_Monthly> HRMS_Sal_Resign_Monthly { get; }
        IRepository<HRMS_Sal_Resign_Monthly_Detail> HRMS_Sal_Resign_Monthly_Detail { get; }
        IRepository<HRMS_Sal_SalaryItem_AccountCode> HRMS_Sal_SalaryItem_AccountCode { get; }
        IRepository<HRMS_Sal_SAPCostCenter> HRMS_Sal_SAPCostCenter { get; }
        IRepository<HRMS_Sal_Tax> HRMS_Sal_Tax { get; }
        IRepository<HRMS_Sal_Tax_Number> HRMS_Sal_Tax_Number { get; }
        IRepository<HRMS_Sal_Taxbracket> HRMS_Sal_Taxbracket { get; }
        IRepository<HRMS_Sal_TaxFree> HRMS_Sal_TaxFree { get; }
        IRepository<HRMS_SYS_Directory> HRMS_SYS_Directory { get; }
        IRepository<HRMS_SYS_Language> HRMS_SYS_Language { get; }
        IRepository<HRMS_SYS_Program> HRMS_SYS_Program { get; }
        IRepository<HRMS_SYS_Program_Function> HRMS_SYS_Program_Function { get; }
        IRepository<HRMS_SYS_Program_Function_Code> HRMS_SYS_Program_Function_Code { get; }
        IRepository<HRMS_SYS_Program_Language> HRMS_SYS_Program_Language { get; }
        IRepository<IDX_g03b> IDX_g03b { get; }
        IRepository<IDX_g26> IDX_g26 { get; }
        IRepository<IDX_g33> IDX_g33 { get; }
        IRepository<IDX_g35b> IDX_g35b { get; }
        IRepository<IDX_g36> IDX_g36 { get; }
        IRepository<IDX_g37> IDX_g37 { get; }
        IRepository<IDX_g59c> IDX_g59c { get; }
        IRepository<IDX_HRMS_Emp_Personal_g01> IDX_HRMS_Emp_Personal_g01 { get; }
        IRepository<IDX_y14> IDX_y14 { get; }
        IRepository<test> test { get; }
        IRepository<HRMS_Sal_FinCategory> HRMS_Sal_FinCategory { get; }
    }
}