export interface EmployExport {
    empID: number;
    partID: number | null;
    partName: string;
    deptID: number;
    deptName: string;
    deptCode: string;
    partCode: string;
    numberID: string;
    fullname: string;
    email: string;
    dateIn: string;
    pnCty: number;
    dateIn_By_Lang: string;
    date_In_Edit: string;
    empPosition: string;
    gbid: number | null;
    empGroup: string;
    phepNam: number | null;
    pnSapXep_DaNghi: number | null;
    pnSapXep_ChuaNghi: number | null;
    pnCaNhan_DaNghi_HP: number | null;
    pnCaNhan_DaNghi_HeThong: number | null;
    pnCaNhan_ChuaNghi: number | null;
    tongPhep_DaNghi: number | null;
    voHieu: string;
    voHieuboolean: boolean;
    createAccount: string;
    year: number | null;
    phep_Nam_Cty: string;
    phep_Nam_Ca_Nhan: string;
    positionID: number | null;
    positionName: string;
    descript: string;
}
